package day16.exception;
/*
	重写之后的方法不能比重写之前的方法抛出更多（更宽泛）的异常，可以更少。
	异常中的关键字：
		异常捕捉：
			try
			catch
			finally

		throws 在方法声明位置上使用，表示上报异常信息给调用者
		throw 手动抛出异常
 */
public class ExceptionTest14 {
}
